### ISSUE TITLE
Bug in mochiweb_request:read_chunk_length/2

### ISSUE THREAD

**Issue by davisp** [mochi/mochiweb#188] opened 2017-06-05 21:05 UTC
I accidentally stumbled across this, but it looks like there's a ten year old bug when reading chunk lengths that doesn't properly skip trailing garbage after the hex encoded length.

https://github.com/mochi/mochiweb/blob/master/src/mochiweb_request.erl#L583

The intended logic for that is to split on any tab, newline, or space. However the original author or (at least someone before the large first commit in the repo) most likely had their editor set up to strip trailing whitespace which inadvertently removed the space after the last character escape. Which changes the logic to checking that C is not a tab, newline, or newline because Erlang will apparently happily apply the $ character escape to any whitespace character.

I only found this due to playing around with some source parsing tooling and this got caught up in one of my checks as an invalid construct. Granted its acceptable to Erlang so its my tool that's broken but I did realize it wasn't intentional in Mochiweb.

**Comment by etrepum** [comment] 2017-06-08 10:58
Do you mind submitting a PR that fixes this issue, since you have everything already there to test & reproduce it?

**Comment by davisp** [comment] 2017-06-08 14:51
Yeah, sorry. Meant to make a note that I'd get to it. Just wanted to write
things down before I moved on and forgot about it.

**Comment by stevewatanabe** [comment] 2019-11-25 18:08
Should this issue be closed as it looks like the fix was incorporated?

**Comment by etrepum** [comment] 2019-11-25 21:24
It looks like the source was reformatted but the bug was not fixed 🤦‍♂

**Comment by etrepum** [comment] 2019-11-25 21:27
Here's the relevant RFC for how this is supposed to behave: https://tools.ietf.org/html/rfc7230#section-4.1

**Comment by stevewatanabe** [comment] 2019-11-25 21:49
Thanks Bob.  I'm new to mochiweb and was skimming the issues and mistakenly thought that particular one had been fixed.

**Comment by BradS2S** [comment] 2022-09-21 06:36
Let me know if this helps. Thanks! https://github.com/mochi/mochiweb/pull/249

**Comment by big-r81** [comment] 2023-08-26 12:37
Can this be closed after #249 gets merged?

**Comment by etrepum** [comment] 2023-08-26 13:41
Yes, this should have been closed.

**Closed by etrepum** 2023-08-26 13:41 UTC
